library(readr)
TelcoCustomerChurn <- read.csv("C:/Users/Unitech1/Desktop/excel/telecom.csv")
View(TelcoCustomerChurn)
churn=subset(TelcoCustomerChurn ,select = c("gender","SeniorCitizen","Partner","Dependents","tenure","PhoneService","MultipleLines","InternetService","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies","Contract","PaperlessBilling","PaymentMethod","MonthlyCharges","TotalCharges","Churn"))
View(churn)
names(churn)
nrow(churn)
ncol(churn)
table(is.na(churn))
sum(is.na(churn))

table(is.na(churn$gender))
is.numeric(churn$gender)
class(churn$gender)
table(churn$gender)
Gender <- factor(churn$gender, levels = c("Female", "Male"), labels = c(0,1))
is.factor(Gender)
table(Gender)
churn$gender<-Gender
is.numeric(churn$SeniorCitizen)
class(churn$SeniorCitizen)
table(churn$SeniorCitizen)
sum(is.na(churn$SeniorCitizen))
range(churn$SeniorCitizen)
is.numeric(churn$Partner)
class(churn$Partner)
is.integer(churn$Partner)
table(is.na(churn$Partner))
table(churn$Partner)
partner<-factor(churn$Partner,levels=c("Yes","No"),labels = c(1,0))
churn$Partner<-partner
is.numeric(churn$Dependents)
class(churn$Dependents)
is.integer(churn$Dependents)
table(is.na(churn$Dependents))
table(churn$Dependents)
dependents<-factor(churn$Dependents,levels=c("Yes","No"),labels=c(1,0))
churn$Dependents<-dependents
is.integer(churn$tenure)
class(churn$tenure)
range(churn$tenure)
table(is.na(churn$tenure))
is.numeric(churn$PhoneService)
class(churn$PhoneService)
is.factor(churn$PhoneService)
table(is.na(churn$PhoneService))
table(churn$PhoneService)
phoneservice<-factor(churn$PhoneService,levels=c("Yes","No"),labels = c(1,0))
churn$PhoneService<-phoneservice
is.integer(churn$MultipleLines)
class(churn$MultipleLines)
table(is.na(churn$MultipleLines))
table(churn$MultipleLines)
multiplelines<-factor(churn$MultipleLines,levels = c("Yes","No","No phone service"),labels = c(1,0,2))
churn$MultipleLines<-multiplelines
is.numeric(churn$InternetService)
class(churn$InternetService)
table(is.na(churn$InternetService))
table(churn$InternetService)
internetservice<-factor(churn$InternetService,levels=c("DSL","Fiber optic","No"),labels=c(1,2,0))
churn$InternetService<-internetservice
is.integer(churn$OnlineSecurity)
class(churn$OnlineSecurity)
table(is.na(churn$OnlineSecurity))
table(churn$OnlineSecurity)
onlinesecurity<-factor(churn$OnlineSecurity,levels=c("Yes","No","No internet service"),labels = c(1,0,2))
churn$OnlineSecurity<-onlinesecurity
is.numeric(churn$OnlineBackup)
class(churn$OnlineBackup)
table(is.na(churn$OnlineBackup))
table(churn$OnlineBackup)
onlinebackup<-factor(churn$OnlineBackup,levels=c("Yes","No","No internet service"),labels = c(1,0,2))
churn$OnlineBackup<-onlinebackup
is.integer(churn$DeviceProtection)
class(churn$DeviceProtection)
table(is.na(churn$DeviceProtection))
table(churn$DeviceProtection)
deviceprotection<-factor(churn$DeviceProtection,levels = c("Yes","No internet service","No"),labels = c(1,2,0))
churn$DeviceProtection<-deviceprotection
is.integer(churn$TechSupport)
class(churn$TechSupport)
table(is.na(churn$TechSupport))
table(churn$TechSupport)
techsupport<-factor(churn$TechSupport,levels = c("Yes","No","No internet service"),labels = c(1,0,2))
churn$TechSupport<-techsupport
is.integer(churn$StreamingTV)
class(churn$StreamingTV)
table(is.na(churn$StreamingTV))
table(churn$StreamingTV)
streamingtv<-factor(churn$StreamingTV,levels = c("Yes","No","No internet service"),labels = c(1,0,2))
streamingtv
view(streamingtv)
churn$StreamingTV<-streamingtv
is.numeric(churn$StreamingMovies)
class(churn$StreamingMovies)
sum(is.na(churn$StreamingMovies))
table(churn$StreamingMovies)
streamingmovies<-factor(churn$StreamingMovies,levels = c("Yes","No","No internet service"),labels = c(1,0,2))
churn$StreamingMovies<-streamingmovies
is.integer(churn$Contract)
class(churn$Contract)
table(is.na(churn$Contract))
table(churn$Contract)
contract<-factor(churn$Contract,levels=c("Month-to-month","One year","Two year"),labels=c(1,2,3))
churn$Contract<-contract
is.integer(churn$PaperlessBilling)
class(churn$PaperlessBilling)
sum(is.na(churn$PaperlessBilling))
table(churn$PaperlessBilling)
paperlessbilling<-factor(churn$PaperlessBilling,levels=c("Yes","No"),labels = c(1,0))
churn$PaperlessBilling<-paperlessbilling
is.integer(churn$PaymentMethod)
class(churn$PaymentMethod)
table(is.na(churn$PaymentMethod))
table(churn$PaymentMethod)
paymentmethod<-factor(churn$PaymentMethod,levels=c("Bank transfer (automatic)","Credit card (automatic)","Electronic check","Mailed check"),labels=c(1,2,3,4))
churn$PaymentMethod<-paymentmethod
is.integer(churn$MonthlyCharges)
class(churn$MonthlyCharges)
range(churn$MonthlyCharges)
table(is.na(churn$MonthlyCharges))
is.integer(churn$TotalCharges)
class(churn$TotalCharges)
range(churn$TotalCharges)
table(is.na(churn$TotalCharges))
mean(churn$TotalCharges,na.rm = TRUE)
churn$TotalCharges[which(is.na(churn$TotalCharges))]<-mean(churn$TotalCharges,na.rm = TRUE)
sum(is.na(churn$TotalCharges))
is.integer(churn$Churn)
class(churn$Churn)
table(is.na(churn$Churn))
table(churn$Churn)
Churn<-factor(churn$Churn,levels=c("Yes","No"),labels = c(1,0))
churn$Churn<-Churn
fix(churn)
library(ResourceSelection)
library(fmsb)
library(ROCR)
library(rpart)
set.seed(100)
a=sample(2,nrow(churn),replace = T,prob = c(0.7,0.3))
train=churn[a==1,]
test=churn[a==2,]
View(train)
View(test)
nrow(train)
nrow(test)
#enter method
log=glm(Churn~.,data=train,family=binomial)
summary(log)
#forward method
log1=step(log,direction="forward")
summary(log1)
#backward method
log2=step(log,direction="backward")
summary(log2)
# Final model fitting
log3=glm(Churn~SeniorCitizen+tenure+MultipleLines+InternetService+OnlineSecurity+TechSupport+StreamingTV+StreamingMovies+Contract+PaperlessBilling+MonthlyCharges+TotalCharges,data=train,family=binomial)
log4=step(log3,direction="backward")
summary(log4)
guru=predict(log4,newdata=subset(test,select=c(1:19)),type='response')
guru1 <- prediction(guru, test$Churn)
guru1
guru2 <- performance(guru1, measure = "tpr", x.measure = "fpr")
plot(guru2)
abline(0,1,lty = 8, col = 'red')
auc=performance(guru1,measure="auc")
auc=auc@y.values[[1]]
auc
#Confusion matrix
y_pred <- ifelse(guru > 0.5, 1 ,0)
cm <- table(test$Churn,y_pred)
cm
#Efficency
Efficency <- sum(diag(cm))/sum(cm)
Efficency

exp(2.589e-01)
