library(readr)
outbreak <- read.csv("c:/users/unitech1/desktop/outbreak.csv")
View(outbreak)
names(outbreak)
class(outbreak)
str(outbreak)
is.na(outbreak$age)
is.numeric(outbreak$age)
class(outbreak$age)
levels(outbreak$age)
levels(outbreak$age) [levels(outbreak$age)=="seven"] <-"7"
levels(outbreak$age) [levels(outbreak$age)=="622"] <-"62"
outbreak$age
range(outbreak$age)
outbreak$age <- as.numeric(outbreak$age)
class(outbreak$age)
range(outbreak$age)
plot(outbreak$age)
 
hist(outbreak$age)
class(outbreak$sex)
is.na(outbreak$sex)
table(outbreak$sex)
SEX <- factor(outbreak$sex, levels= c("Male","Female"), labels = c(1, 2))
is.factor(SEX)
class(SEX)
outbreak$sex <- SEX
class(outbreak$sex)
na.omit(outbreak$sex)
levels(outbreak$sex)
class(outbreak$timesupper)
range(outbreak$timesupper)
is.na(outbreak$timesupper)
range(outbreak$timesupper, na.rm = TRUE)
supper_date <- "19400418"
supper_dt <- paste(supper_date, outbreak$timesupper)
head(supper_dt)
class(supper_dt) 
supper_datetime <- ymd_hm(supper_dt)
head(supper_datetime)
class(supper_datetime)
supper_datetime
outbreak$supperdatetime <- supper_datetime
library(stringr)
onsettime_new <- str_pad(outbreak$onsettime, 4, pad = "0")
head(onsettime_new)
table(outbreak$onsetdate)
onsetdate_new <- str_replace(outbreak$onsetdate, '18-Apr', '19400418')
onsetdate_new <- str_replace(onsetdate_new, '19-Apr', 
outbreak$onsetdatetime <- onset_datetime
hist(outbreak$onsetdatetime, breaks="hours")
str(outbreak)
'19400419')
head(onsetdate_new)
onsetdt <- paste(onsetdate_new, onsettime_new, sep = "")
head(onsetdt)
onsetdt <- str_replace(onsetdt, 'NANA', 'NA')
head(onsetdt)
onset_datetime <- ymd_hm(onsetdt)
head(onset_datetime)
class(onset_datetime)