library(readr)
revenue <- read.csv("c:/Users/Unitech1/Desktop/excel/revenue.csv")
View(revenue)
names(revenue)
str(revenue)
is.na(revenue)
class(revenue$Indian.revenue)
plot(revenue$Indian.revenue,  col=c("red"))
hist(revenue$Indian.revenue)
levels(revenue$Indian.revenue)
mean(revenue$Indian.revenue)
table(revenue$Indian.revenue)
class(revenue$Imports.income)
is.na(revenue$Imports.income)
plot(revenue$Imports.income)
levels(revenue$Imports.income)
mean(revenue$Imports.income)
class(revenue$Exports.income)
is.na(revenue$Exports.income)
plot(revenue$Exports.income)
mean(revenue$Exports.income)
class(revenue$Tax.income)
is.na(revenue$Tax.income)
plot(revenue$Tax.income)
mean(revenue$Tax.income)
table(revenue$Tax.income)
class(revenue$Medical)
is.na(revenue$Medical)
plot(revenue$Medical)
range(revenue$Medical)
mean(revenue$Medical)
class(revenue$Tourism)
is.na(revenue$Tourism)
plot(revenue$Tourism)
mean(revenue$Tourism)
cor(revenue)
lmdls <- lm(Indian.revenue ~ Imports.income , data=revenue) 
lmdls
summary(lmdls)
lmdas <- lm(Indian.revenue ~ Exports.income , data = revenue)
lmdas
summary(lmdas)
lmdbs <- lm(Indian.revenue ~ Tax.income , data = revenue)
lmdbs
summary(lmdbs)
lmdcs <- lm(Indian.revenue ~ Medical , data = revenue)
lmdcs
summary(lmdcs)
lmdds <- lm(Indian.revenue ~ Tourism , data = revenue)
lmdds 
summary(lmdds)
lmdl <- lm(Indian.revenue ~ Imports.income + Exports.income + Tax.income + Medical + Tourism , data = revenue)
lmdl
summary(lmdl)
lmdls <- lm(Indian.revenue ~ Imports.income + Exports.income - Tax.income - Medical - Tourism, data = revenue) 
lmdls 
summary(lmdls)
