library(readr)
salary <- read.csv("c:/users/unitech3/desktop/salary.csv")
View(salary)
nrow(salary)
ncol(salary)
names(salary)
str(salary)
is.na(salary)
class(salary$gender)
is.na(salary$gender)            
levels(salary$gender)
class(salary$bdate)
is.na(salary$bdate)
class(salary$educ)
is.na(salary$educ)
levels(salary$educ)
